spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:postgresql://localhost:5432/ResolveMate
    username: postgres
    password: postgres

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: localhost
    port: 1025
    username: admin@resolvemate.com
    password: admin

app:
  security:
    jwt:
      secret-key: 493F2571314538494B4E47592A47293D5A4865673771446D636E7267786D7927
      expiration: 86400000

  file:
    max-size: 10485760

  cache:
    duration: 24